version: "3.9" # or just remove this line as Docker says it's obsolete

services:
  noco:
    image: nocodb/nocodb:0.264.4
    container_name: noco
    ports:
      - "8080:8080"
    volumes:
      - ./nocodb:/usr/app/data/
    restart: unless-stopped
    environment:
      NC_ADMIN_EMAIL: admin@example.com
      NC_ADMIN_PASSWORD: 12341234
