name: Run Tests

on:
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.16
        options: --privileged
        ports:
          - 8080:8080

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Start NocoDB container
        run: |
          docker-compose up -d
          for i in {1..30}; do
            STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}" http://localhost:8080/)
            if [ "$STATUS_CODE" -eq 200 ]; then
              echo "NocoDB is up!"
              break
            else
              echo "Waiting for NocoDB to start... (HTTP status: $STATUS_CODE)"
              sleep 2
            fi
          done

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest
