# .github/workflows/ui-testing.yaml
name: Selenium UI Tests

on:
  # Manual trigger (Run workflow button)
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to test against"
        required: true
        default: "staging"
        type: choice
        options:
          - development
          - staging
          - production
      browser:
        description: "Browser to run tests on"
        required: true
        default: "chrome"
        type: choice
        options:
          - chrome
          - firefox

  # Automatic trigger on PRs to main
  pull_request:
    branches:
      - main

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1 # Fetch only the latest commit to speed up the checkout process
          repository: yosefshawah/nocodb-UI-testing # Replace with your UI testing repo
          token: ${{ secrets.UI_TESTING_GITHUB_TOKEN }} # Use the token to access the repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chrome & ChromeDriver
        run: |
          sudo apt update
          # Removed libgconf-2-4 (deprecated)
          sudo apt install -y wget unzip xvfb libxi6 libgbm-dev libnss3 libxshmfence1 libasound2
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          CHROME_VERSION=$(google-chrome --version | grep -oP "\d+\.\d+\.\d+\.\d+")
          # Download matching ChromeDriver
          wget -q -O chromedriver.zip "https://storage.googleapis.com/chrome-for-testing-public/$CHROME_VERSION/linux64/chromedriver-linux64.zip" || \
            wget -q -O chromedriver.zip "https://chromedriver.storage.googleapis.com/$CHROME_VERSION/chromedriver_linux64.zip"
          unzip chromedriver.zip
          sudo mv chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver

      - name: Run Selenium tests
        env:
          HEADLESS: true
          OLLAMA_URL: http://52.18.93.49:8080/
        run: |
          pytest tests/ -v
